/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RoomIdRouteImport } from './routes/$roomId'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiRoomIdRouteImport } from './routes/api/$roomId'

const RoomIdRoute = RoomIdRouteImport.update({
  id: '/$roomId',
  path: '/$roomId',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRoomIdRoute = ApiRoomIdRouteImport.update({
  id: '/api/$roomId',
  path: '/api/$roomId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/$roomId': typeof RoomIdRoute
  '/api/$roomId': typeof ApiRoomIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/$roomId': typeof RoomIdRoute
  '/api/$roomId': typeof ApiRoomIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/$roomId': typeof RoomIdRoute
  '/api/$roomId': typeof ApiRoomIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$' | '/$roomId' | '/api/$roomId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$' | '/$roomId' | '/api/$roomId'
  id: '__root__' | '/' | '/$' | '/$roomId' | '/api/$roomId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  RoomIdRoute: typeof RoomIdRoute
  ApiRoomIdRoute: typeof ApiRoomIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$roomId': {
      id: '/$roomId'
      path: '/$roomId'
      fullPath: '/$roomId'
      preLoaderRoute: typeof RoomIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$roomId': {
      id: '/api/$roomId'
      path: '/api/$roomId'
      fullPath: '/api/$roomId'
      preLoaderRoute: typeof ApiRoomIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  RoomIdRoute: RoomIdRoute,
  ApiRoomIdRoute: ApiRoomIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
